# Generated by Django 3.2.9 on 2021-11-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('user_type', models.IntegerField(choices=[(0, 'Employee'), (1, 'Employer')], default=0)),
                ('national_id', models.CharField(max_length=14)),
                ('city', models.CharField(max_length=200)),
                ('experience_level', models.IntegerField(choices=[(0, 'Junior'), (1, 'Mid'), (2, 'Senior')], default=0)),
                ('bio_description', models.TextField()),
                ('profile_view', models.IntegerField(default=0)),
                ('programming_languages', models.ManyToManyField(to='core_app.ProgrammingLanguage')),
            ],
        ),
    ]
