# Generated by Django 3.2.9 on 2021-11-05 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('experience_level', models.IntegerField(choices=[(0, 'Junior'), (1, 'Mid'), (2, 'Senior')], default=0)),
                ('post_description', models.TextField(blank=True)),
                ('page_view', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='appuser',
            name='bio_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='national_id',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.CreateModel(
            name='PostApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected')], default=0)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.appuser')),
                ('jobpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.jobpost')),
            ],
        ),
        migrations.AddField(
            model_name='jobpost',
            name='jobapplicants',
            field=models.ManyToManyField(through='core_app.PostApplicant', to='core_app.AppUser'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='core_app.appuser'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='programming_languages',
            field=models.ManyToManyField(to='core_app.ProgrammingLanguage'),
        ),
    ]
